### ISSUE TITLE
Can't Bash into the container

### ISSUE THREAD

**Issue by Auriosi** [spritsail/fivem#15]
With most containers, I can just run "docker exec -it <containername> /bin/bash" except that this doesn't work with this container. I need to change the permissions on it so I can apply the new config, but I can't do that right now without being able to Bash into it. How would one Bash into this container?

**Comment by Adam-Ant** [comment]
The base operating system of this container (Alpine) does not use bash, it instead uses the much lighter sh. You should be able to run `docker exec -ti <containerName> sh` instead to get to a shell.

As a note, in 99% of containers, you can use sh instead of bash and it will usually work - Bash isn't usually found in the better built and optimized images.
